services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - "9092:9092"  # Expose the OUTSIDE listener
    networks:
      - app-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092  # Use different ports for each listener
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Set the inter-broker listener name

  # scheduling_extractor service with port mapping to end with 1 (8001, 27011) on host machine
  scheduling_extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduling_extractor
    ports:
      - "8001:8000"
    command: sh -c "cd scheduling_extractor && gunicorn --bind 0.0.0.0:8000 scheduling_extractor.wsgi:application"
    networks:
      - app-network
    environment:
      # override .env file
      - MONGO_HOST=scheduling_extractor_mongodb
      - MONGO_PORT=27017

  scheduling_extractor_mongodb:
    image: mongo:6
    container_name: scheduling_extractor_mongodb
    ports:
      - "27011:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
